---
title: "Initial data survey"
author: "LJM"
date: "`r Sys.Date()`"
link-citations: true
bibliography: bibliography.bib
biblio-style: "alpha" #https://www.overleaf.com/learn/latex/Bibtex_bibliography_styles
#csl: "../uppsala-universitet-institutionen-for-biologisk-grundutbildning.csl"
documentclass: report
output:
  bookdown::pdf_document2:
    keep_tex: no
    latex_engine: xelatex
    #highlight: pygments #Other options: default, tango, kate, monochrome, espresso, zenburn, haddock, and textmate
    #theme: spacelab
    pandoc_args: ["--variable", "subparagraph",
                "--top-level-division","chapter"] # Could also be section 
  html_document: 
    toc: TRUE
    toc_float: TRUE
    code_folding: show
    highlight: tango
    number_sections: TRUE
    self_contained: TRUE
    smart: TRUE # To be figured out when this is useful
    theme: journal
  pdf_document:
    toc: TRUE
    toc_depth: 2
    highlight: tango # This appears to be the same as default
    number_sections: TRUE
  bookdown::html_document2:
    highlight: tango
    theme: journal
    split_by: none # only generate a single output page
    self_contained: TRUE
    toc: yes
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
      print: FALSE
    code_folding: show
    number_sections: TRUE
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The data

```{r message=FALSE, warning=FALSE}
rm(list=ls())
library(tidyverse)
```

**What is in the files?**

## Which bins belong to which fOTUS?

```{r}
fOTUs <- read_csv(file = "../data/fOTUs.csv", col_names = TRUE)
glimpse(fOTUs)
```

```{r}
colnames(fOTUs)
```

## What bin does each cluster of orthologous genes (COG) belong to?

```{r}
bin2cogs <- read_csv(file = "../data/bin2cogs.csv", col_names = TRUE)
glimpse(bin2cogs)
```

```{r}
colnames(bin2cogs)
```

## Stats on all fOTUed bins

```{r}
stats_on_all_fOTUed_bins <- read_csv(file = "../analyses/stats_on_all_fOTUed_bins.csv", col_names = TRUE)
glimpse(stats_on_all_fOTUed_bins)
```

```{r}
colnames(stats_on_all_fOTUed_bins)
```

## Stats on representative bins

```{r}
stats_on_representative_bins <- read_csv(file = "../analyses/stats_on_representative_bins.csv", col_names = TRUE)
glimpse(stats_on_representative_bins)
```

```{r}
colnames(stats_on_representative_bins)
```

# Session info

```{r}
sessionInfo()
```

